openapi: 3.1.0
x-stoplight:
  id: i9mp04xl94sy9
info:
  title: portmone-direct
  version: '1.0'
  description: ''
  summary: portmone direct api
servers:
  - url: 'http://localhost:3000'
paths:
  /api:
    post:
      summary: 'api'
      x-microcks-dispatcher: URI_PARAMS
      x-microcks-dispatcherRules: method
      operationId: post-api
      parameters:
        - examples:
            bills.createByPhone:
              value: bills.createByPhone
            bills.pay:
              value: bills.pay
            bills.get:
              value: bills.get
            bills.date:
              value: bills.date
            bills.paymentOrder:
              value: bills.paymentOrder
          name: method
          schema:
            type: string
          in: query
          required: true
      responses:
        '200':
          description: ''
          content:
            application/xml:
              examples:
                bills.createByPhone:
                  value: |-
                    <?xml version="1.0" encoding="utf-8"?>
                    <rsp status="ok">
                        <bill id="1191117777">
                            <payee id="2065">Київстар</payee>
                            <contractNumber title="Номер телефону (без +380) ">673334411</contractNumber>
                            <attribute1 />
                            <attribute2 title="Номер квитанцii Київстар"></attribute2>
                            <attribute3 />
                            <attribute4 />
                            <bill_attribute1 />
                            <bill_attribute2 />
                            <bill_attribute3 />
                            <bill_attribute4 />
                            <date>19.07.2022</date>
                            <description>Рахунок створений автоматично для поповнення балансу</description>
                            <amount>105.00</amount>
                            <debt>0.00</debt>
                            <sum>105.00</sum>
                            <status>created</status>
                            <paidAmount />
                            <payDate />
                            <payee_export_flag />
                            <auth_code />
                            <transaction_id />
                            <payment_point />
                        </bill>
                    </rsp>
                bills.pay:
                  value: |-
                    <?xml version="1.0" encoding="utf-8"?>
                    <rsp status="fail">
                        <error code="p009">Помилка при оновленні параметрів лічильника</error>
                    </rsp>
                bills.get:
                  value: |-
                    <?xml version="1.0" encoding="utf-8"?>
                    <rsp status="ok">
                            <bill id="1191117777">
                                <name>Київстар</name>
                                <contractNumber title="Номер телефону (без +380) ">964332082</contractNumber>
                                <attribute1 />
                                <bill_attribute1 />
                                <attribute2 title="Номер квитанцii Київстар"></attribute2>
                                <bill_attribute2 />
                                <attribute3 />
                                <bill_attribute3 />
                                <attribute4 />
                                <bill_attribute4 />
                                <status>PAYED</status>
                                <paidAmount>153.00</paidAmount>
                                <payDate>12.09.2022 16:29:41</payDate>
                                <transaction_id />
                                <payee_export_date />
                                <payee_export_flag>E</payee_export_flag>
                                <bank_commission>-0.50</bank_commission>
                            </bill>
                    </rsp>
                bills.date:
                  value: |-
                    <?xml version="1.0" encoding="utf-8"?>
                    <rsp status="ok">
                        <bills>
                            <bill id="1256188387">
                                <name>Київстар</name>
                                <contractNumber title="Номер телефону (без +380) ">958779322</contractNumber>
                                <attribute1 />
                                <bill_attribute1 />
                                <attribute2 title="Номер квитанцii Київстар"></attribute2>
                                <bill_attribute2 />
                                <attribute3 />
                                <bill_attribute3 />
                                <attribute4 />
                                <bill_attribute4 />
                                <status>PAYED</status>
                                <paidAmount>153.00</paidAmount>
                                <payDate>21.06.2022 16:29:41</payDate>
                                <transaction_id />
                                <payee_export_date />
                                <payee_export_flag>Y</payee_export_flag>
                                <bank_commission>-0.50</bank_commission>
                            </bill>
                            <bill id="1256190580">
                                <name>Київстар</name>
                                <contractNumber title="Номер телефону (без +380) ">958779322</contractNumber>
                                <attribute1 />
                                <bill_attribute1 />
                                <attribute2 title="Номер квитанцii Київстар"></attribute2>
                                <bill_attribute2 />
                                <attribute3 />
                                <bill_attribute3 />
                                <attribute4 />
                                <bill_attribute4 />
                                <status>PAYED</status>
                                <paidAmount>100.00</paidAmount>
                                <payDate>21.06.2022 16:30:35</payDate>
                                <transaction_id />
                                <payee_export_date />
                                <payee_export_flag>Y</payee_export_flag>
                                <bank_commission>-0.50</bank_commission>
                            </bill>
                            <bill id="1256193075">
                                <name>Київстар</name>
                                <contractNumber title="Номер телефону (без +380) ">958779322</contractNumber>
                                <attribute1 />
                                <bill_attribute1 />
                                <attribute2 title="Номер квитанцii Київстар"></attribute2>
                                <bill_attribute2 />
                                <attribute3 />
                                <bill_attribute3 />
                                <attribute4 />
                                <bill_attribute4 />
                                <status>PAYED</status>
                                <paidAmount>100.00</paidAmount>
                                <payDate>21.06.2022 16:30:35</payDate>
                                <transaction_id />
                                <payee_export_date />
                                <payee_export_flag>Y</payee_export_flag>
                                <bank_commission>-0.50</bank_commission>
                            </bill>
                            <bill id="1256194764">
                                <name>Київстар</name>
                                <contractNumber title="Номер телефону (без +380) ">958779322</contractNumber>
                                <attribute1 />
                                <bill_attribute1 />
                                <attribute2 title="Номер квитанцii Київстар"></attribute2>
                                <bill_attribute2 />
                                <attribute3 />
                                <bill_attribute3 />
                                <attribute4 />
                                <bill_attribute4 />
                                <status>created</status>
                                <paidAmount>100.00</paidAmount>
                                <payDate>21.06.2022 16:30:35</payDate>
                                <transaction_id />
                                <payee_export_date />
                                <payee_export_flag>B</payee_export_flag>
                                <bank_commission>-0.50</bank_commission>
                            </bill>
                        </bills>                            
                        <bill id="1256196802">
                                <name>Київстар</name>
                                <contractNumber title="Номер телефону (без +380) ">958779322</contractNumber>
                                <attribute1 />
                                <bill_attribute1 />
                                <attribute2 title="Номер квитанцii Київстар"></attribute2>
                                <bill_attribute2 />
                                <attribute3 />
                                <bill_attribute3 />
                                <attribute4 />
                                <bill_attribute4 />
                                <status>PAYED</status>
                                <paidAmount>100.00</paidAmount>
                                <payDate>21.06.2022 16:30:35</payDate>
                                <transaction_id />
                                <payee_export_date />
                                <payee_export_flag>R</payee_export_flag>
                                <bank_commission>-0.50</bank_commission>
                            </bill>
                        </bills>                            
                        <bill id="1256199946">
                                <name>Київстар</name>
                                <contractNumber title="Номер телефону (без +380) ">958779322</contractNumber>
                                <attribute1 />
                                <bill_attribute1 />
                                <attribute2 title="Номер квитанцii Київстар"></attribute2>
                                <bill_attribute2 />
                                <attribute3 />
                                <bill_attribute3 />
                                <attribute4 />
                                <bill_attribute4 />
                                <status>PAYED</status>
                                <paidAmount>100.00</paidAmount>
                                <payDate>21.06.2022 16:30:35</payDate>
                                <transaction_id />
                                <payee_export_date />
                                <payee_export_flag>E</payee_export_flag>
                                <bank_commission>-0.50</bank_commission>
                            </bill>
                        </bills>                            
                        <bill id="1256203326">
                                <name>Київстар</name>
                                <contractNumber title="Номер телефону (без +380) ">958779322</contractNumber>
                                <attribute1 />
                                <bill_attribute1 />
                                <attribute2 title="Номер квитанцii Київстар"></attribute2>
                                <bill_attribute2 />
                                <attribute3 />
                                <bill_attribute3 />
                                <attribute4 />
                                <bill_attribute4 />
                                <status>PAYED</status>
                                <paidAmount>100.00</paidAmount>
                                <payDate>21.06.2022 16:30:35</payDate>
                                <transaction_id />
                                <payee_export_date />
                                <payee_export_flag>N</payee_export_flag>
                                <bank_commission>-0.50</bank_commission>
                            </bill>
                        </bills>
                    </rsp>
                bills.paymentOrder:
                  value: |-
                    <?xml version="1.0" encoding="utf-8"?>
                    <rsp status="ok">
                        <paymentOrder>
                            <record id="1645849"/>
                        </paymentOrder>
                    </rsp>
