openapi: 3.1.0
x-stoplight:
  id: i9mp04xl94sy9
info:
  title: portmone-direct
  version: '1.0'
  description: ''
  summary: portmone direct api
servers:
  - url: 'http://localhost:3000'
paths:
  /api:
    post:
      summary: 'api'
      x-microcks-dispatcher: URI_PARAMS
      x-microcks-dispatcherRules: method
      operationId: post-api
      parameters:
        - examples:
            bills.createByPhone:
              value: bills.createByPhone
            bills.pay:
              value: bills.pay
            bills.get:
              value: bills.get         
          name: method
          schema:
            type: string
          in: query
          required: true
      responses:
        '200':
          description: ''
          content:
            application/xml:
              examples:
                bills.createByPhone:
                  value: |-
                    <?xml version="1.0" encoding="utf-8"?>
                    <rsp status="ok">
                        <bill id="1191116006">
                            <payee id="2065">Київстар</payee>
                            <contractNumber title="Номер телефону (без +380) ">673334411</contractNumber>
                            <attribute1 />
                            <attribute2 title="Номер квитанцii Київстар"></attribute2>
                            <attribute3 />
                            <attribute4 />
                            <bill_attribute1 />
                            <bill_attribute2 />
                            <bill_attribute3 />
                            <bill_attribute4 />
                            <date>14.06.2022</date>
                            <description>Рахунок створений автоматично для поповнення балансу</description>
                            <amount>100.00</amount>
                            <debt>0.00</debt>
                            <sum>100.00</sum>
                            <status>created</status>
                            <paidAmount />
                            <payDate />
                            <payee_export_flag />
                            <auth_code />
                            <transaction_id />
                            <payment_point />
                        </bill>
                    </rsp>
                bills.pay:
                  value: |-
                    <?xml version="1.0" encoding="utf-8"?>
                    <rsp status="fail">
                        <error code="p004">Помилка при оновленні параметрів лічильника</error>
                    </rsp>
                bills.get:
                  value: |-
                    <?xml version="1.0" encoding="utf-8"?>
                    <rsp status="fail">
                        <bill id="1191116006">
                            <payee id="2065">Київстар</payee>
                            <contractNumber title="Номер телефону (без +380) ">673334411</contractNumber>
                            <attribute1 />
                            <attribute2 title="Номер квитанцii Київстар"></attribute2>
                            <attribute3 />
                            <attribute4 />
                            <bill_attribute1 />
                            <bill_attribute2 />
                            <bill_attribute3 />
                            <bill_attribute4 />
                            <date>14.06.2022</date>
                            <description>Рахунок створений автоматично для поповнення балансу</description>
                            <amount>100.00</amount>
                            <debt>0.00</debt>
                            <sum>100.00</sum>
                            <status>PAYED</status>
                            <paidAmount />
                            <payDate />
                            <payee_export_flag />
                            <auth_code />
                            <transaction_id />
                            <payment_point />
                        </bill>
                    </rsp>
